spring:
    h2:
        :console:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost/Bakery
        username: postgres
        password: postgresql
#        url: jdbc:h2:mem:testdb
#        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        generate-ddl: true
    mail:
        host: smtp.mail.ru
        username: mailzell@inbox.ru
        password: ZellRus34
        port: 465
        protocol: smtps
mail:
    gebug: true
        
bakery:
    title: my bakery
    host: 192.168.34.63:8080
    
upload:
    path: src/main/resources/static/img
    
    