# --spring.config.location=classpath:application_dev.yml

spring:
    datasource:
        #url: jdbc:postgresql://localhost:5432/bakery
        url: jdbc:postgresql://localhost:5432/Bakery
        username: postgres
        password: postgresql
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        generate-ddl: true
    mail:
        host: smtp.mail.ru
        username: mailzell@inbox.ru
        password: ZellRus34
        port: 465
        protocol: smtps
    session:
        jdbc:
            initialize-schema: always
            table-name: SPRING_SESSION
    flyway:
        enabled: true
        baseline-on-migrate: true
    rabbitmq:
        host: 3.8.121.161
        port: 5672
        username: springUser
        password: CG56XNLI4PKxUBeIv611CEJC9GzXHSdHmFLP34kz
mail:
    gebug: true
        
bakery:
    title: my bakery
    host: 192.168.34.63:8080
    
upload:
    #path: img
    path: src\\main\\resources\\static\\img
    
server:
    error:
        path: /error
app:
    rabbit:
        topicExchangeName: bakery-kitchen
        queueName: orders
        routingKey: orders
    