spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/bakery
        username: postgres
        password: postgresql
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        generate-ddl: true
    application:
        name: bakery
#    mail:
#        host: smtp.mail.ru
#        username: mailzell@inbox.ru
#        password: ZellRus34
#        port: 465
#        protocol: smtps
    session:
        jdbc:
            initialize-schema: always
            table-name: SPRING_SESSION
    flyway:
        enabled: true
        baseline-on-migrate: true
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        lease-renewal-interval-in-seconds: 2
#mail:
#    gebug: true
       
bakery:
    title: my bakery
    host: http://3.8.157.121
#    host: 192.168.34.63:8080
    
upload:
    path: img
    #path: src\\main\\resources\\static\\images
    
server:
    error:
        path: /error