spring:
    datasource:
        #url: jdbc:postgresql://localhost:5432/bakery
        url: jdbc:postgresql://localhost:5432/Bakery
        username: postgres
        password: postgresql
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        generate-ddl: true
    mail:
        host: smtp.mail.ru
        username: mailzell@inbox.ru
        password: ZellRus34
        port: 465
        protocol: smtps
    session:
        jdbc:
            initialize-schema: always
            table-name: SPRING_SESSION
    flyway:
        enabled: true
        baseline-on-migrate: true
mail:
    gebug: true
        
bakery:
    title: my bakery
    #host: http://18.133.219.180
    host: http://192.168.34.63:8080
    
upload:
    #path: img
    path: src\\main\\resources\\static\\images
    
server:
    error:
        path: /error
    
    