spring:
    h2:
        :console:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost/Bakery
        username: postgres
        password: postgresql
#        url: jdbc:h2:mem:testdb
#        initialization-mode: always
    jpa:
#        hibernate:
#            ddl-auto: none
        show-sql: true
        generate-ddl: true
        
bakery:
    title: my bakery
    
upload:
    path: src/main/resources/static/img